import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "Project Uas SDA",
    template: "%s | Project Uas SDA",
  },
  description: "Generated by Rafly",
  authors: [{ name: "Rafly", url: "https://github.com/Raflysaputra23" }],
  keywords: ["Bracket", "TicTacToe", "Next JS", "TypeScript", "Project UAS SDA"],
  robots: "index, follow",
  openGraph: {
    title: "Project Uas SDA",
    description: "Generated by Rafly",
    url: "https://project-uas-sda.vercel.app/",
    siteName: "Project Uas SDA",
    images: [
      {
        url: "https://project-uas-sda.vercel.app/og.png",
        width: 800,
        height: 600,
      },
    ],
    locale: "id_ID",
    type: "website",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`poppins-regular antialiased bg-slate-200`}
      >
        {children}
      </body>
    </html>
  );
}
